name: Custom Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      env:
        INSTALLATION_ROOT: ./
              
    - name: install dependencies
      run: sudo apt-get install build-essential git qt5-default qt5-qmake libpq5 libxml2 pkg-config xml2 libxml2-dev libpq-dev libqt5svg5-dev
      
    - name: prepare make
    #  run: qmake pgmodeler.pro
      run: qmake -r CONFIG+=release PREFIX=$INSTALLATION_ROOT BINDIR=$INSTALLATION_ROOT PRIVATEBINDIR=$INSTALLATION_ROOT PRIVATELIBDIR=$INSTALLATION_ROOT/lib pgmodeler.pro
      
    - name: run make
      run: make
      
    - name: run make install
      run: sudo make install
          
      # prepare artifact
    - name: Prepare artifact
      run: tar -cvzf ${{ github.workspace }}/pgmodeler-dist.tar.gz ${{ github.workspace }}/pgmodeler/build/

    # upload artifact
    - uses: actions/upload-artifact@v2-preview
      with:
        name: pgmodeler
        path: ${{ github.workspace }}/pgmodeler-dist.tar.gz
