name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: run windows deploy script
      run: sudo windeploy.sh
     
    - name: make tar file artifact
      run: tar -czvf /home/user/pgmodeler.tar.gz dist/*
      
    - uses: actions/upload-artifact@v1
      with:
        name: pgmodeler
        path: /home/user/pgmodeler.tar.gz
