name: Custom Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      env:
        PREFIX : /home/user/pgmodeler/build 
        BINDIR : /home/user/pgmodeler/build 
        PRIVATEBINDIR : /home/user/pgmodeler/build 
        PRIVATELIBDIR : /home/user/pgmodeler/build 
        PLUGINSDIR : /home/user/pgmodeler/build/plugins 
        SHAREDIR : /home/user/pgmodeler/build 
        CONFDIR : /home/user/pgmodeler/build/conf 
        DOCDIR : /home/user/pgmodeler/build 
        LANGDIR : /home/user/pgmodeler/build/lang 
        SAMPLESDIR : /home/user/pgmodeler/build/samples 
        SCHEMASDIR : /home/user/pgmodeler/build/schemas
        INSTALLATION_ROOT: /home/user/pgmodeler/build
      
    #- name: checkout latest tags
    #  run: git checkout tags/v0.9.2
      
    - name: install dependencies
      run: sudo apt-get install build-essential git qt5-default qt5-qmake libpq5 libxml2 pkg-config xml2 libxml2-dev libpq-dev libqt5svg5-dev
      
    - name: prepare make
    #  run: qmake pgmodeler.pro
      run: qmake -r CONFIG+=release PREFIX=$INSTALLATION_ROOT BINDIR=$INSTALLATION_ROOT PRIVATEBINDIR=$INSTALLATION_ROOT PRIVATELIBDIR=$INSTALLATION_ROOT/lib pgmodeler.pro
      
    - name: run make
      run: make
      
    - name: run make install
      run: sudo make install
      
    - name: make tar file artifact
      run: tar -czvf /home/user/pgmodeler-dist.tar.gz ./dist/*
    - name: make tar file artifact
      run: tar -czvf /home/user/pgmodeler-build.tar.gz ./build/*
      
    - uses: actions/upload-artifact@v1
      with:
        name: pgmodeler
        path: /home/user/pgmodeler-linux-dist.tar.gz
    
    - uses: actions/upload-artifact@v1
      with:
        name: pgmodeler
        path: /home/user/pgmodeler-linux-build.tar.gz
