name: Deploy linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: run linux deploy script
      run: sudo ./linuxdeploy.sh
     
    - name: make tar file artifact
      run: tar -czvf /home/user/pgmodeler-dist.tar.gz ./dist/*
    - name: make tar file artifact
      run: tar -czvf /home/user/pgmodeler-build.tar.gz ./build/*
      
    - uses: actions/upload-artifact@v1
      with:
        name: pgmodeler
        path: /home/user/pgmodeler-linux-dist.tar.gz
    
    - uses: actions/upload-artifact@v1
      with:
        name: pgmodeler
        path: /home/user/pgmodeler-linux-build.tar.gz
