name: Deploy Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: run windows deploy script
      run: sudo bash ./windeploy.sh
     
    - name: make tar file artifact
      run: tar -czvf /home/user/pgmodeler-dist.tar.gz ./dist/*
    - name: make tar file artifact
      run: tar -czvf /home/user/pgmodeler-build.tar.gz ./build/*
      
    - uses: actions/upload-artifact@v1
      with:
        name: pgmodeler
        path: /home/user/pgmodeler-win-dist.tar.gz
    
    - uses: actions/upload-artifact@v1
      with:
        name: pgmodeler
        path: /home/user/pgmodeler-win-build.tar.gz
